# Generated by Django 4.0.4 on 2022-05-20 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('north london', 'North London'), ('west london', 'West London'), ('south london', 'South London'), ('east london', 'East London')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=50)),
                ('time', models.CharField(max_length=5)),
                ('players_needed', models.CharField(max_length=1)),
                ('description', models.TextField(unique_for_date='published')),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('area', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sesh.area')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesh_post', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-published',),
            },
        ),
    ]
