# Generated by Django 4.0.4 on 2022-05-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(choices=[('North London', 'North London'), ('West London', 'West London'), ('South London', 'South London'), ('East London', 'East London')], max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='difficulty',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=50),
        ),
    ]
